show_controls: true
start_with: ''
mode: chat-instruct
chat_style: cai-chat
chat-instruct_command: |-
  Continue the chat dialogue below. Write a single reply for the character "<|character|>".

  <|prompt|>
prompt-default: QA
prompt-notebook: QA
character: Assistant
name1: You
user_bio: ''
custom_system_message: ''
preset: min_p
max_new_tokens: 512
max_new_tokens_min: 1
max_new_tokens_max: 4096
prompt_lookup_num_tokens: 0
max_tokens_second: 0
max_updates_second: 0
auto_max_new_tokens: true
ban_eos_token: false
add_bos_token: true
skip_special_tokens: true
stream: true
static_cache: false
truncation_length: 8192
seed: -1
custom_stopping_strings: ''
custom_token_bans: ''
show_after: ''
negative_prompt: ''
autoload_model: false
dark_theme: true
default_extensions: []
instruction_template_str: |-
  {%- set ns = namespace(found=false) -%}
  {%- for message in messages -%}
      {%- if message['role'] == 'system' -%}
          {%- set ns.found = true -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if not ns.found -%}
      {{- '' + 'Below is an instruction that describes a task. Write a response that appropriately completes the request.' + '\n\n' -}}
  {%- endif %}
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- '' + message['content'] + '\n\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{-'### Instruction:\n' + message['content'] + '\n\n'-}}
          {%- else -%}
              {{-'### Response:\n' + message['content'] + '\n\n' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if add_generation_prompt -%}
      {{-'### Response:\n'-}}
  {%- endif -%}
chat_template_str: |-
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {%- if message['content'] -%}
              {{- message['content'] + '\n\n' -}}
          {%- endif -%}
          {%- if user_bio -%}
              {{- user_bio + '\n\n' -}}
          {%- endif -%}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{- name1 + ': ' + message['content'] + '\n'-}}
          {%- else -%}
              {{- name2 + ': ' + message['content'] + '\n' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}

