.*(llama|alpac|vicuna|guanaco|koala|llava|wizardlm|metharme|pygmalion-7b|wizard-mega|openbuddy|vigogne|h2ogpt-research|manticore):
  model_type: 'llama'
.*(opt-|opt_|opt1|opt3|optfor|galactica|galpaca|pygmalion-350m):
  model_type: 'opt'
.*(gpt-j|gptj|gpt4all-j|malion-6b|pygway|pygmalion-6b|dolly-v1):
  model_type: 'gptj'
.*(gpt-neox|koalpaca-polyglot|polyglot.*koalpaca|polyglot-ko|polyglot_ko|pythia|stablelm|incite|dolly-v2|polycoder|h2ogpt-oig|h2ogpt-oasst1|h2ogpt-gm):
  model_type: 'gpt_neox'
.*llama:
  model_type: 'llama'
.*bloom:
  model_type: 'bloom'
llama-65b-gptq-3bit:
  groupsize: 'None'
.*(4bit|int4):
  wbits: 4
.*(3bit|int3):
  wbits: 3
.*(-2bit|_2bit|int2-):
  wbits: 2
.*(-1bit|_1bit|int1-):
  wbits: 1
.*(8bit|int8):
  wbits: 8
.*(-7bit|_7bit|int7-):
  wbits: 7
.*(-6bit|_6bit|int6-):
  wbits: 6
.*(-5bit|_5bit|int5-):
  wbits: 5
.*(-gr32-|-32g-|groupsize32|-32g$):
  groupsize: 32
.*(-gr64-|-64g-|groupsize64|-64g$):
  groupsize: 64
.*(gr128|128g|groupsize128):
  groupsize: 128
.*(gr1024|1024g|groupsize1024):
  groupsize: 1024
.*(oasst|openassistant-|stablelm-7b-sft-v7-epoch-3):
  mode: 'instruct'
  instruction_template: 'Open Assistant'
  skip_special_tokens: false
(?!.*galactica)(?!.*reward).*openassistant:
  mode: 'instruct'
  instruction_template: 'Open Assistant'
  skip_special_tokens: false
(?!.*v0)(?!.*1.1)(?!.*1_1)(?!.*stable)(?!.*chinese).*vicuna:
  mode: 'instruct'
  instruction_template: 'Vicuna-v0'
.*vicuna.*v0:
  mode: 'instruct'
  instruction_template: 'Vicuna-v0'
.*vicuna.*(1.1|1_1|1.3|1_3):
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
.*wizard.*vicuna:
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
.*stable.*vicuna:
  mode: 'instruct'
  instruction_template: 'StableVicuna'
(?!.*chat).*chinese-vicuna:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*chinese-vicuna.*chat:
  mode: 'instruct'
  instruction_template: 'Chinese-Vicuna-Chat'
.*alpaca:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*alpaca-native-4bit:
  mode: 'instruct'
  instruction_template: 'Alpaca'
  wbits: 4
  groupsize: 128
.*galactica:
  skip_special_tokens: false
.*dolly-v[0-9]-[0-9]*b:
  mode: 'instruct'
  instruction_template: 'Alpaca'
  skip_special_tokens: false
  custom_stopping_strings: '"### End"'
.*koala:
  mode: 'instruct'
  instruction_template: 'Koala'
.*chatglm:
  mode: 'instruct'
  instruction_template: 'ChatGLM'
.*metharme:
  mode: 'instruct'
  instruction_template: 'Metharme'
.*llava:
  mode: 'instruct'
  model_type: 'llama'
  instruction_template: 'LLaVA'
  custom_stopping_strings: '"\n###"'
.*raven:
  mode: 'instruct'
  instruction_template: 'RWKV-Raven'
.*moss-moon.*sft:
  mode: 'instruct'
  instruction_template: 'MOSS'
.*stablelm-tuned:
  mode: 'instruct'
  instruction_template: 'StableLM'
  truncation_length: 4096
.*stablelm-base:
  truncation_length: 4096
.*wizardlm:
  mode: 'instruct'
  model_type: 'llama'
  instruction_template: 'WizardLM'
.*galactica.*finetuned:
  mode: 'instruct'
  instruction_template: 'Galactica Finetuned'
.*galactica.*-v2:
  mode: 'instruct'
  instruction_template: 'Galactica v2'
(?!.*finetuned)(?!.*-v2).*galactica:
  mode: 'instruct'
  instruction_template: 'Galactica'
.*guanaco:
  mode: 'instruct'
  instruction_template: 'Guanaco non-chat'
.*baize:
  mode: 'instruct'
  instruction_template: 'Baize'
.*mpt-.*instruct:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*mpt-.*chat:
  mode: 'instruct'
  instruction_template: 'MPT-Chat'
(?!.*-flan-)(?!.*-t5-).*lamini-:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*incite.*chat:
  mode: 'instruct'
  instruction_template: 'INCITE-Chat'
.*incite.*instruct:
  mode: 'instruct'
  instruction_template: 'INCITE-Instruct'
.*wizard.*mega:
  mode: 'instruct'
  instruction_template: 'Wizard-Mega'
.*ziya-:
  mode: 'instruct'
  instruction_template: 'Ziya'
.*koalpaca:
  mode: 'instruct'
  instruction_template: 'KoAlpaca'
.*openbuddy:
  mode: 'instruct'
  instruction_template: 'OpenBuddy'
(?!.*chat).*vigogne:
  mode: 'instruct'
  instruction_template: 'Vigogne-Instruct'
.*vigogne.*chat:
  mode: 'instruct'
  instruction_template: 'Vigogne-Chat'
.*(llama-deus|supercot|llama-natural-instructions|open-llama-0.3t-7b-instruct-dolly-hhrlhf|open-llama-0.3t-7b-open-instruct):
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*bactrian:
  mode: 'instruct'
  instruction_template: 'Bactrian'
.*(h2ogpt-oig-|h2ogpt-oasst1-|h2ogpt-research-oasst1-):
  mode: 'instruct'
  instruction_template: 'H2O-human_bot'
.*h2ogpt-gm-:
  mode: 'instruct'
  instruction_template: 'H2O-prompt_answer'
.*manticore:
  mode: 'instruct'
  instruction_template: 'Manticore Chat'
.*bluemoonrp-(30|13)b:
  mode: 'instruct'
  instruction_template: 'Bluemoon'
  truncation_length: 4096
.*Nous-Hermes-13b:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*airoboros:
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
.*WizardLM-30B-V1.0:
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
TheBloke_WizardLM-30B-GPTQ:
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
.*alpa(cino|sta):
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*hippogriff:
  mode: 'instruct'
  instruction_template: 'Hippogriff'
.*gpt4all-.*-snoozy:
  mode: 'instruct'
  instruction_template: 'WizardLM'
.*lazarus:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*guanaco-.*(7|13|33|65)b:
  mode: 'instruct'
  instruction_template: 'Guanaco'
.*hypermantis:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*open-llama-.*-open-instruct:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*starcoder-gpteacher-code-instruct:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*tulu:
  mode: 'instruct'
  instruction_template: 'Tulu'
.*chronos:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*samantha:
  mode: 'instruct'
  instruction_template: 'Samantha'
.*wizardcoder:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*starchat-beta:
  mode: 'instruct'
  instruction_template: 'Starchat-Beta'
.*minotaur:
  mode: 'instruct'
  instruction_template: 'Minotaur'
.*minotaur-15b:
  truncation_length: 8192
.*orca_mini:
  mode: 'instruct'
  instruction_template: 'Orca Mini'
.*landmark:
  truncation_length: 8192
.*superhot-8k:
  truncation_length: 8192
.*xgen.*-inst:
  truncation_length: 8192
  instruction_template: 'Vicuna-v0'
